version: '3.7'

services:

  sonarqube:
    # https://hub.docker.com/_/sonarqube
    image: sonarqube:7.9.1-community
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - type: volume
        source: sonarqube_conf
        target: /opt/sonarqube/conf
      - type: volume
        source: sonarqube_data
        target: /opt/sonarqube/data
      - type: volume
        source: sonarqube_extensions
        target: /opt/sonarqube/extensions

  db:
    # https://hub.docker.com/_/postgres
    image: postgres:12
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - type: volume
        source: postgresql_data
        target: /var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
